// <auto-generated />
using LevelUpInventorySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LevelUpInventorySystem.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20240418165907_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelUpInventorySystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explore incredible places far from the Mushroom Kingdom",
                            Inventory = 10,
                            Name = "Super Mario Odyssey",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discover Hyrule like never before",
                            Inventory = 8,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Join Kratos on a deep and reflective journey",
                            Inventory = 12,
                            Name = "God of War",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Experience an epic tale of life in America's unforgiving heartland",
                            Inventory = 6,
                            Name = "Red Dead Redemption 2",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Drop into a massive online battle with up to 100 players",
                            Inventory = 15,
                            Name = "Fortnite: Battle Royale",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
